// example.ts — module vitrine : montre chaque type de bloc dans l'aperçu (« Voir un exemple »).
// Contenu volontairement sans fait financier : il parle des modules eux-mêmes. Les données du
// graphique sont fictives et le disent.
export const EXAMPLE_MODULE = {
  version_prompt: "2.1",
  module: {
    titre: "Vitrine : à quoi peut ressembler ton module",
    auteur: "HypeInvest",
    resume: "Tous les blocs possibles, pour te donner des idées avant d'écrire le tien.",
    niveau: "découverte",
    duree_lecture_min: 4,
    etiquettes: ["bases"],
    ton: "léger",
    emoji: "🧭",
    blocs: [
      { type: "texte", titre: "Un module, c'est quoi ?", contenu: "Un petit contenu à lire en quelques minutes, écrit par un membre du club avec l'aide de son IA. Il raconte ou fait découvrir un sujet lié à l'argent, comme on le ferait autour d'un café. Pas de cours, pas d'examen : juste l'envie de partager." },
      { type: "chiffre_cle", valeur: "4", label: "champs obligatoires", detail: "titre, auteur, résumé et blocs : tout le reste est libre." },
      { type: "chiffre_cle", valeur: "20", label: "types de blocs", detail: "à mélanger dans l'ordre que tu veux." },
      { type: "chiffre_cle", valeur: "3 à 8", label: "minutes de lecture", detail: "court, c'est mieux." },
      { type: "saviez_vous", texte: "Si ton idée ne rentre dans aucune case, le bloc « libre » est fait pour ça : décris ce que tu imagines et on le construira." },
      { type: "citation", texte: "Écris comme tu parlerais à un ami curieux.", source: "Le conseil de la maison" },
      { type: "attention", niveau: "attention", texte: "Un module explique, il ne conseille jamais d'acheter ou de vendre quoi que ce soit." },
      { type: "attention", niveau: "info", texte: "Chaque chiffre précis doit avoir une source, sinon il est présenté comme une estimation." },
      { type: "schema", titre: "Le chemin d'un module", etapes: ["Copier le prompt", "Discuter avec ton IA", "Relire la version lisible", "Coller le JSON dans l'aperçu", "L'envoyer à Clément"], explication: "Rien n'est publié sans relecture." },
      { type: "chronologie", titre: "Une soirée d'écriture", etapes: [{ quand: "20 h", titre: "Les questions", detail: "Ton IA te demande ce qui te passionne." }, { quand: "20 h 15", titre: "Le plan", detail: "Tu valides l'accroche et la chute." }, { quand: "20 h 45", titre: "La relecture", detail: "Tu ajustes jusqu'à ce que ça te ressemble." }] },
      { type: "comparaison", gauche: { titre: "Une formation", points: ["On étudie", "Un programme fixe", "Un examen à la fin"] }, droite: { titre: "Un module", points: ["On découvre", "La forme que tu veux", "Juste pour le plaisir"] }, conclusion: "Ici, on est clairement à droite." },
      { type: "tableau", titre: "Quel bloc pour quelle idée ?", colonnes: ["Ton idée", "Bloc conseillé"], lignes: [["Raconter une histoire", "chronologie"], ["Mettre deux choses face à face", "comparaison"], ["Partager ton vécu", "temoignage"], ["Faire réfléchir", "quiz ou vrai_faux"]] },
      { type: "graphique", titre: "Exemple de graphique en barres", forme: "barres", unite: "pts", donnees: [{ label: "Lundi", valeur: 12 }, { label: "Mardi", valeur: 18 }, { label: "Mercredi", valeur: 9 }, { label: "Jeudi", valeur: 22 }], legende: "Données fictives, seulement pour montrer le rendu." },
      { type: "graphique", titre: "Exemple de courbe", forme: "ligne", unite: "pts", donnees: [{ label: "Jan", valeur: 100 }, { label: "Fév", valeur: 104 }, { label: "Mar", valeur: 98 }, { label: "Avr", valeur: 110 }, { label: "Mai", valeur: 115 }], legende: "Données fictives, seulement pour montrer le rendu." },
      { type: "liste", titre: "Pour réussir ton module", ordonnee: true, items: ["Une accroche qui donne envie", "Des blocs variés", "Une idée à retenir à la fin"] },
      { type: "vocabulaire", termes: [{ terme: "Prompt", definition: "Le texte que tu colles dans ton IA pour lui expliquer ce que tu attends." }, { terme: "JSON", definition: "Le format du fichier final : l'app le transforme en jolie page." }] },
      { type: "exemple", titre: "Le cas de Léa (personnage inventé)", scenario: "Léa veut parler de son premier budget. Son IA lui pose des questions, propose un plan en cinq blocs, puis Léa ajoute ses propres anecdotes.", chiffres: [{ label: "Blocs", valeur: "5" }, { label: "Temps d'écriture", valeur: "environ 1 h" }] },
      { type: "temoignage", texte: "Ici, l'auteur raconte son vécu à la première personne. C'est souvent le passage que les lecteurs préfèrent.", auteur: "Un futur auteur" },
      { type: "faq", questions: [{ q: "Je ne suis pas expert, je peux écrire ?", r: "Oui : ton vécu et ta curiosité suffisent, l'IA t'aide pour la forme." }, { q: "Combien de temps ça prend ?", r: "Une soirée suffit pour un module court." }] },
      { type: "quiz", question: "Combien de champs sont obligatoires dans un module ?", choix: ["2", "4", "10"], bonne_reponse: 1, explication: "Titre, auteur, résumé et blocs. Tout le reste est facultatif." },
      { type: "vrai_faux", affirmation: "Un module peut recommander d'acheter une action.", reponse: false, explication: "Jamais : on explique et on fait découvrir, on ne conseille pas." },
      { type: "cartes", cartes: [{ recto: "Bloc libre", verso: "Pour une idée qui ne rentre dans aucune case." }, { recto: "Aperçu", verso: "Pour voir ton module avant de l'envoyer." }, { recto: "Sources", verso: "Pour chaque chiffre ou fait précis." }] },
      { type: "libre", description: "Une idée originale non prévue", contenu: "Ce bloc affiche le contenu tel quel. Clément verra ta description et pourra construire un vrai bloc sur mesure." },
    ],
  },
  sources: [],
  notes_pour_clement: "Module de démonstration, non publié.",
};
