// quiz-bank.ts — la RÉSERVE du quiz du jour : des questions de culture boursière, vérifiées,
// qui ne vieillissent pas. Elle sert les jours où la routine de nuit n'a pas écrit de question
// (memory/fund/quiz.json). Le choix du jour est déterministe (même question pour tout le monde).
import type { QuizQuestion } from "./quiz";

type BankQ = Omit<QuizQuestion, "date">;

export const QUIZ_BANK: BankQ[] = [
  {
    theme: "bases", level: "facile",
    question: "Que mesure le PER (Price Earnings Ratio) d'une action ?",
    choices: ["Le prix payé pour 1 € de bénéfice annuel", "Le dividende versé chaque année", "La dette de l'entreprise", "La croissance de ses ventes"],
    answer: 0,
    explanation: "PER = cours ÷ bénéfice par action. Un PER de 20 veut dire qu'on paie 20 € pour 1 € de bénéfice annuel : plus il est haut, plus le marché attend de croissance… ou plus l'action est chère.",
    source: { name: "AMF — glossaire de l'épargnant" },
  },
  {
    theme: "histoire", level: "facile",
    question: "Le « jeudi noir » qui lance le krach de 1929 a eu lieu à…",
    choices: ["Londres", "Paris", "New York", "Tokyo"],
    answer: 2,
    explanation: "Le 24 octobre 1929 à Wall Street. Le Dow Jones a mis 25 ans, jusqu'en 1954, à retrouver son sommet de 1929.",
    source: { name: "Federal Reserve History — The Stock Market Crash of 1929" },
  },
  {
    theme: "psychologie", level: "moyen",
    question: "Selon Kahneman et Tversky, la douleur de perdre 100 € pèse à peu près autant que le plaisir de gagner…",
    choices: ["50 €", "100 €", "200 €", "1 000 €"],
    answer: 2,
    explanation: "On ressent les pertes environ deux fois plus fort que les gains (coefficient ≈ 2,25). D'où la tentation de garder trop longtemps ses lignes perdantes.",
    source: { name: "Tversky & Kahneman (1992), « Advances in Prospect Theory »" },
  },
  {
    theme: "bases", level: "facile",
    question: "Qu'est-ce qu'un ETF (ou « tracker ») ?",
    choices: ["Une action d'une banque américaine", "Un produit d'épargne garanti par l'État", "Un fonds coté en bourse qui réplique un indice", "Une obligation d'entreprise"],
    answer: 2,
    explanation: "Un ETF suit un indice (CAC 40, MSCI World…). En une seule ligne, on achète tout un panier d'entreprises, en général avec des frais faibles.",
    source: { name: "AMF — Les fonds indiciels cotés (ETF)" },
  },
  {
    theme: "crypto", level: "facile",
    question: "Combien de bitcoins existeront au maximum ?",
    choices: ["21 millions", "100 millions", "1 milliard", "Aucune limite"],
    answer: 0,
    explanation: "Le protocole plafonne l'offre à 21 millions. La création ralentit à chaque « halving », environ tous les 4 ans.",
    source: { name: "Satoshi Nakamoto, livre blanc Bitcoin (2008) et code source" },
  },
  {
    theme: "bases", level: "moyen",
    question: "1 000 € placés à 7 % par an, intérêts réinvestis : combien après 10 ans, environ ?",
    choices: ["1 070 €", "1 700 €", "1 970 €", "2 500 €"],
    answer: 2,
    explanation: "1 000 × 1,07¹⁰ ≈ 1 967 € : les intérêts produisent eux-mêmes des intérêts. Sans les réinvestir, on n'aurait que 1 700 €.",
    source: { name: "Calcul des intérêts composés" },
  },
  {
    theme: "histoire", level: "moyen",
    question: "Après son sommet de mars 2000, de combien le Nasdaq a-t-il chuté jusqu'en octobre 2002 ?",
    choices: ["Environ −20 %", "Environ −45 %", "Environ −78 %", "Environ −95 %"],
    answer: 2,
    explanation: "De 5 048 points (10 mars 2000) à 1 114 (9 octobre 2002). Une bonne histoire, internet, ne justifiait pas n'importe quel prix.",
    source: { name: "Nasdaq Composite, historique de l'indice" },
  },
  {
    theme: "fiscalite", level: "moyen",
    question: "Quel est le plafond de versements d'un PEA classique ?",
    choices: ["20 000 €", "75 000 €", "150 000 €", "Aucun plafond"],
    answer: 2,
    explanation: "150 000 € de versements (225 000 € en cumulant avec un PEA-PME). Après 5 ans, les gains échappent à l'impôt sur le revenu mais restent soumis aux prélèvements sociaux.",
    source: { name: "Service-public.fr — Plan d'épargne en actions" },
  },
  {
    theme: "bases", level: "facile",
    question: "Quand les taux d'intérêt montent, le prix des obligations déjà émises…",
    choices: ["Monte", "Baisse", "Ne bouge pas", "Double"],
    answer: 1,
    explanation: "Une ancienne obligation verse un coupon plus faible que les nouvelles : pour rester attractive, son prix baisse. Les taux sont la « gravité » des marchés.",
    source: { name: "Banque de France — ABC de l'économie" },
  },
  {
    theme: "histoire", level: "facile",
    question: "Quelle banque américaine a fait faillite le 15 septembre 2008 ?",
    choices: ["Goldman Sachs", "Lehman Brothers", "JPMorgan", "Morgan Stanley"],
    answer: 1,
    explanation: "La faillite de Lehman Brothers, la plus grosse de l'histoire américaine, a transformé la crise des subprimes en crise financière mondiale.",
    source: { name: "Federal Reserve History — The Great Recession" },
  },
  {
    theme: "psychologie", level: "facile",
    question: "Refuser de vendre une action « tant qu'elle n'est pas revenue à mon prix d'achat » illustre…",
    choices: ["La diversification", "Le biais d'ancrage", "L'effet de levier", "L'arbitrage"],
    answer: 1,
    explanation: "Le prix d'achat n'intéresse que nous : le marché l'ignore. La bonne question est « l'achèterais-je aujourd'hui à ce prix ? ».",
    source: { name: "Tversky & Kahneman (1974), « Judgment under Uncertainty »" },
  },
  {
    theme: "bases", level: "facile",
    question: "Comment calcule-t-on la capitalisation boursière d'une entreprise ?",
    choices: ["Chiffre d'affaires × 10", "Bénéfice net − dettes", "Cours de l'action × nombre d'actions", "Somme des dividendes versés"],
    answer: 2,
    explanation: "C'est ce que vaut l'entreprise en bourse à un instant donné : le prix d'une action multiplié par le nombre total d'actions.",
    source: { name: "Euronext — glossaire" },
  },
  {
    theme: "histoire", level: "moyen",
    question: "Le 19 octobre 1987 (« lundi noir »), le Dow Jones a perdu en une seule séance environ…",
    choices: ["5 %", "12 %", "22 %", "40 %"],
    answer: 2,
    explanation: "−22,6 % : la plus forte baisse en une journée de son histoire. Les « coupe-circuits » qui suspendent la cotation en cas de chute brutale datent de là.",
    source: { name: "Federal Reserve History — Stock Market Crash of 1987" },
  },
  {
    theme: "bases", level: "facile",
    question: "Investir la même somme chaque mois, quel que soit le cours, s'appelle…",
    choices: ["Le day trading", "La vente à découvert", "L'effet de levier", "L'investissement programmé (DCA)"],
    answer: 3,
    explanation: "C'est ce que fait le club avec ses apports mensuels : on achète plus de parts quand c'est bas, moins quand c'est haut, sans chercher le « bon moment ».",
    source: { name: "AMF — Investir progressivement" },
  },
  {
    theme: "crypto", level: "moyen",
    question: "Le « halving » du bitcoin, c'est…",
    choices: ["La division par deux de la récompense des mineurs", "La division du prix par deux", "Une scission du réseau", "Une taxe européenne"],
    answer: 0,
    explanation: "Tous les 210 000 blocs, environ 4 ans, la récompense des mineurs est divisée par deux. Le dernier a eu lieu en avril 2024.",
    source: { name: "Code source de Bitcoin (bloc 840 000, avril 2024)" },
  },
  {
    theme: "bases", level: "moyen",
    question: "Une banque centrale relève ses taux de 25 points de base. Cela fait…",
    choices: ["2,5 %", "0,25 %", "25 %", "0,025 %"],
    answer: 1,
    explanation: "1 point de base = 0,01 %. 25 points de base = 0,25 % : c'est le pas habituel des banques centrales.",
    source: { name: "Banque de France — glossaire" },
  },
  {
    theme: "histoire", level: "difficile",
    question: "Le Nikkei japonais a culminé fin 1989. Quand a-t-il retrouvé ce sommet ?",
    choices: ["1995", "2007", "2024", "Jamais"],
    answer: 2,
    explanation: "Le 22 février 2024, après 34 ans. Le record du 29 décembre 1989 (38 915 points) rappelle qu'acheter très cher peut coûter des décennies.",
    source: { name: "Nikkei Inc. — historique du Nikkei 225" },
  },
  {
    theme: "psychologie", level: "facile",
    question: "Acheter une action « parce que tout le monde en parle et qu'elle a déjà pris +80 % » relève surtout…",
    choices: ["D'une analyse fondamentale", "D'une couverture de risque", "De la peur de rater le train (FOMO)", "D'un rééquilibrage"],
    answer: 2,
    explanation: "Le « fear of missing out » pousse à acheter après la hausse, souvent au pire moment. Une thèse, un prix et une règle de sortie valent mieux qu'un emballement.",
    source: { name: "AMF — Les biais comportementaux de l'investisseur" },
  },
  {
    theme: "bases", level: "facile",
    question: "À quoi sert surtout la diversification ?",
    choices: ["À garantir un gain", "À réduire le risque lié à une seule entreprise", "À payer moins d'impôts", "À doubler le rendement"],
    answer: 1,
    explanation: "Répartir sur beaucoup d'entreprises, de secteurs et de pays limite l'impact d'une mauvaise surprise. Elle ne supprime pas le risque du marché dans son ensemble.",
    source: { name: "AMF — Diversifier ses placements" },
  },
  {
    theme: "histoire", level: "moyen",
    question: "La « tulipomanie », souvent citée comme l'une des premières bulles spéculatives, a éclaté en…",
    choices: ["1637, aux Provinces-Unies", "1720, en Angleterre", "1929, aux États-Unis", "1990, au Japon"],
    answer: 0,
    explanation: "En février 1637, le prix des bulbes de tulipe s'effondre. Les historiens débattent de son ampleur réelle, mais le mot est resté pour désigner une bulle.",
    source: { name: "Anne Goldgar, « Tulipmania » (2007)" },
  },
  {
    theme: "bases", level: "moyen",
    question: "Une action à 60 € verse 3 € de dividende par an. Son rendement est de…",
    choices: ["3 %", "5 %", "20 %", "0,5 %"],
    answer: 1,
    explanation: "Rendement = dividende ÷ cours = 3 ÷ 60 = 5 %. Attention : un rendement très élevé signale parfois un cours qui s'effondre ou un dividende menacé.",
    source: { name: "Calcul du rendement du dividende" },
  },
  {
    theme: "bases", level: "facile",
    question: "Un ordre « à cours limité » à 50 € pour acheter une action…",
    choices: ["S'exécute tout de suite, quel que soit le prix", "Ne s'exécute qu'à 50 € ou moins", "Ne s'exécute qu'au-dessus de 50 €", "Est annulé si le marché ouvre en baisse"],
    answer: 1,
    explanation: "On fixe le prix maximum qu'on accepte de payer. Contrairement à l'ordre « au marché », il protège d'un mauvais prix, mais peut ne jamais s'exécuter.",
    source: { name: "AMF — Les différents types d'ordres de bourse" },
  },
  {
    theme: "histoire", level: "moyen",
    question: "Après la chute du Covid (février-mars 2020), en combien de temps le S&P 500 a-t-il retrouvé son record ?",
    choices: ["Environ 5 mois", "Environ 3 ans", "Environ 10 ans", "Jamais"],
    answer: 0,
    explanation: "Record le 19 février, creux le 23 mars (−34 %), nouveau record le 18 août 2020 : l'un des rebonds les plus rapides de l'histoire. Vendre au creux coûtait cher.",
    source: { name: "S&P Dow Jones Indices — historique du S&P 500" },
  },
  {
    theme: "psychologie", level: "moyen",
    question: "Juger les fonds d'investissement en ne regardant que ceux qui existent encore aujourd'hui, c'est…",
    choices: ["Une prime de risque", "L'aversion au risque", "Un indice pondéré", "Le biais du survivant"],
    answer: 3,
    explanation: "Les fonds ratés ont fermé et disparu des classements : les survivants donnent une image trop belle des performances moyennes.",
    source: { name: "Elton, Gruber & Blake (1996), « Survivorship Bias and Mutual Fund Performance »" },
  },
  {
    theme: "bases", level: "facile",
    question: "Un dividende, c'est…",
    choices: ["Un impôt sur les plus-values", "Une part du bénéfice versée aux actionnaires", "Le prix d'achat d'une action", "Une commission du courtier"],
    answer: 1,
    explanation: "L'entreprise reverse une partie de ses bénéfices à ses actionnaires, en général une ou plusieurs fois par an. Rien ne l'y oblige : il peut baisser ou disparaître.",
    source: { name: "AMF — glossaire de l'épargnant" },
  },
  {
    theme: "bases", level: "moyen",
    question: "Avec 3 % d'inflation par an, 1 000 € laissés sur un compte à 0 % perdent en 10 ans environ… de pouvoir d'achat.",
    choices: ["3 %", "26 %", "50 %", "Rien"],
    answer: 1,
    explanation: "1 ÷ 1,03¹⁰ ≈ 0,74 : il ne reste qu'environ 74 % du pouvoir d'achat. Le cash « sans risque » perd lentement de sa valeur.",
    source: { name: "Calcul du pouvoir d'achat" },
  },
  {
    theme: "histoire", level: "facile",
    question: "Quelle société Warren Buffett a-t-il transformée en conglomérat à partir de 1965 ?",
    choices: ["BlackRock", "Vanguard", "Berkshire Hathaway", "Goldman Sachs"],
    answer: 2,
    explanation: "Une ancienne filature textile devenue un géant de l'assurance, du rail et de l'énergie. Greg Abel lui a succédé comme directeur général début 2026.",
    source: { name: "Berkshire Hathaway — lettres aux actionnaires" },
  },
  {
    theme: "bases", level: "moyen",
    question: "Le VIX, surnommé « l'indice de la peur », mesure…",
    choices: ["La volatilité attendue du S&P 500 sur 30 jours", "Le nombre de faillites", "Le prix de l'or", "Le moral des ménages"],
    answer: 0,
    explanation: "Calculé par le Cboe à partir des prix des options. Il bondit dans les paniques (plus de 80 en mars 2020) et reste bas quand le marché est serein.",
    source: { name: "Cboe — VIX Index" },
  },
  {
    theme: "bases", level: "moyen",
    question: "On dit que la courbe des taux est « inversée » quand…",
    choices: ["Les taux sont négatifs", "Les taux longs sont plus bas que les taux courts", "La banque centrale baisse ses taux", "L'inflation dépasse 10 %"],
    answer: 1,
    explanation: "Normalement, prêter longtemps rapporte plus. Une inversion montre que le marché attend un ralentissement : elle a souvent précédé les récessions américaines, sans être infaillible.",
    source: { name: "Federal Reserve Bank of St. Louis (FRED) — écart 10 ans - 2 ans" },
  },
  {
    theme: "psychologie", level: "facile",
    question: "Ne lire que les articles qui confirment son avis sur une action s'appelle…",
    choices: ["Le biais de confirmation", "Le biais du survivant", "La loi de Pareto", "L'effet de richesse"],
    answer: 0,
    explanation: "On cherche ce qui nous donne raison. Le remède : écrire le meilleur argument contre sa thèse avant d'acheter. C'est ce que fait l'IA à chaque décision.",
    source: { name: "Raymond Nickerson (1998), « Confirmation Bias »" },
  },
  {
    theme: "bases", level: "facile",
    question: "Que signifie « vendre à découvert » ?",
    choices: ["Vendre une action détenue depuis longtemps", "Parier sur la baisse en vendant des titres empruntés", "Vendre sans frais", "Vendre à un proche hors bourse"],
    answer: 1,
    explanation: "On emprunte des actions, on les vend, puis on espère les racheter moins cher pour les rendre. La perte possible est illimitée si le cours monte.",
    source: { name: "AMF — La vente à découvert" },
  },
  {
    theme: "histoire", level: "facile",
    question: "En quelle année l'euro a-t-il été lancé sur les marchés financiers, avant les pièces et billets ?",
    choices: ["1992", "1999", "2001", "2004"],
    answer: 1,
    explanation: "Le 1er janvier 1999 pour les marchés et les virements ; les pièces et billets sont arrivés le 1er janvier 2002.",
    source: { name: "Banque centrale européenne — histoire de l'euro" },
  },
  {
    theme: "bases", level: "facile",
    question: "Quand une entreprise rachète ses propres actions, en général…",
    choices: ["Le nombre d'actions baisse et le bénéfice par action monte", "Elle se déclare en faillite", "Le nombre d'actions augmente", "Elle doit doubler son dividende"],
    answer: 0,
    explanation: "Moins d'actions pour le même bénéfice : chaque action en représente une part plus grande. C'est une autre façon de rendre de l'argent aux actionnaires.",
    source: { name: "AMF — Les programmes de rachat d'actions" },
  },
  {
    theme: "histoire", level: "moyen",
    question: "Qui a inventé « Mr. Market », ce voisin lunatique qui propose chaque jour un prix pour vos actions ?",
    choices: ["Warren Buffett", "John Maynard Keynes", "Benjamin Graham", "Peter Lynch"],
    answer: 2,
    explanation: "Dans « L'investisseur intelligent » (1949). Le marché est à notre service, pas à nos ordres : on peut ignorer ses prix délirants et en profiter.",
    source: { name: "Benjamin Graham, « The Intelligent Investor » (1949)" },
  },
  {
    theme: "bases", level: "moyen",
    question: "Avec un rendement de 8 % par an, en combien de temps un capital double-t-il, environ ?",
    choices: ["4 ans", "9 ans", "15 ans", "25 ans"],
    answer: 1,
    explanation: "Règle de 72 : 72 ÷ 8 = 9 ans (1,08⁹ ≈ 2). Pratique pour estimer de tête l'effet des intérêts composés.",
    source: { name: "Règle de 72 (approximation des intérêts composés)" },
  },
  {
    theme: "bases", level: "moyen",
    question: "Le MSCI World regroupe environ combien d'entreprises ?",
    choices: ["Une centaine", "Environ 500", "Environ 1 400", "Plus de 10 000"],
    answer: 2,
    explanation: "Environ 1 400 grandes et moyennes entreprises de 23 pays développés. Les États-Unis en pèsent environ 70 % : « monde » ne veut pas dire équilibré.",
    source: { name: "MSCI — fiche de l'indice MSCI World" },
  },
  {
    theme: "bases", level: "facile",
    question: "Laquelle de ces entreprises ne fait PAS partie des « Sept Magnifiques » américaines ?",
    choices: ["Nvidia", "Meta", "Tesla", "Netflix"],
    answer: 3,
    explanation: "Les Sept Magnifiques : Apple, Microsoft, Alphabet, Amazon, Meta, Nvidia et Tesla. Elles pèsent une part record du S&P 500.",
    source: { name: "S&P Dow Jones Indices — poids des composantes du S&P 500" },
  },
  {
    theme: "fiscalite", level: "moyen",
    question: "Sur un PEA, après combien d'années peut-on retirer de l'argent sans clôturer le plan ni payer d'impôt sur le revenu ?",
    choices: ["1 an", "3 ans", "5 ans", "10 ans"],
    answer: 2,
    explanation: "Après 5 ans, les retraits n'entraînent plus la clôture (loi Pacte, 2019) et les gains sont exonérés d'impôt sur le revenu. Les prélèvements sociaux restent dus.",
    source: { name: "Service-public.fr — Plan d'épargne en actions" },
  },
  {
    theme: "bases", level: "facile",
    question: "Où siège la Banque centrale européenne ?",
    choices: ["Bruxelles", "Francfort", "Paris", "Luxembourg"],
    answer: 1,
    explanation: "À Francfort. Elle fixe les taux directeurs de la zone euro, avec pour mission principale une inflation proche de 2 % à moyen terme.",
    source: { name: "Banque centrale européenne" },
  },
  {
    theme: "bases", level: "facile",
    question: "Rééquilibrer un portefeuille, c'est…",
    choices: ["Tout vendre en cas de baisse", "Revenir aux poids voulus en allégeant ce qui a trop monté", "N'acheter que ce qui monte", "Changer de courtier chaque année"],
    answer: 1,
    explanation: "Quand une ligne a beaucoup monté, elle pèse trop lourd. On l'allège pour revenir à l'allocation voulue : c'est vendre un peu haut et racheter un peu bas, avec méthode.",
    source: { name: "AMF — Gérer son portefeuille dans la durée" },
  },
  {
    theme: "crypto", level: "facile",
    question: "Un « stablecoin » comme l'USDC cherche à…",
    choices: ["Valoir toujours 1 dollar", "Doubler chaque année", "Remplacer l'or", "Verser un dividende"],
    answer: 0,
    explanation: "Il est adossé à des réserves (dollars, bons du Trésor) pour garder une valeur stable. Sa solidité dépend entièrement de la qualité de ces réserves.",
    source: { name: "Circle — rapports de réserves de l'USDC" },
  },
  {
    theme: "bases", level: "difficile",
    question: "Le ratio de Sharpe d'un placement compare…",
    choices: ["Le cours au bénéfice", "Le rendement en plus du sans-risque, divisé par la volatilité", "La dette aux fonds propres", "Le dividende au cours"],
    answer: 1,
    explanation: "Il mesure le rendement obtenu par unité de risque pris. Deux fonds à +8 % ne se valent pas si l'un a deux fois plus de secousses.",
    source: { name: "William F. Sharpe (1966), « Mutual Fund Performance »" },
  },
  {
    theme: "bases", level: "facile",
    question: "Un « marché baissier » (bear market) désigne en général une baisse depuis un sommet d'au moins…",
    choices: ["5 %", "10 %", "20 %", "50 %"],
    answer: 2,
    explanation: "Par convention : −10 % = correction, −20 % = marché baissier. Ces baisses font partie de la vie normale des marchés, pas une exception.",
    source: { name: "S&P Dow Jones Indices — convention de place" },
  },
  {
    theme: "histoire", level: "facile",
    question: "Le CAC 40 a démarré avec une base de 1 000 points. Quand ?",
    choices: ["En 1958", "En 1968", "Fin 1987", "En 2000"],
    answer: 2,
    explanation: "Base 1 000 au 31 décembre 1987. Il suit les 40 valeurs les plus représentatives de la bourse de Paris (Euronext).",
    source: { name: "Euronext — règles de l'indice CAC 40" },
  },
  {
    theme: "bases", level: "facile",
    question: "Les frais courants d'un ETF (TER) sont prélevés…",
    choices: ["Une seule fois, à l'achat", "Chaque année, sur la valeur du fonds", "Seulement en cas de perte", "Uniquement à la revente"],
    answer: 1,
    explanation: "Ils sont déduits en continu de la valeur du fonds, en % par an. 0,2 % ou 1 % par an, ça paraît proche, mais sur 20 ans l'écart se compte en milliers d'euros.",
    source: { name: "AMF — Les frais des placements" },
  },
  {
    theme: "bases", level: "facile",
    question: "Une IPO, c'est…",
    choices: ["Une faillite", "Une introduction en bourse", "Un rachat par un concurrent", "Un dividende exceptionnel"],
    answer: 1,
    explanation: "« Initial Public Offering » : l'entreprise vend pour la première fois ses actions au public. Les premiers jours sont souvent très volatils.",
    source: { name: "Euronext — S'introduire en bourse" },
  },
];
